# This file was generated by GoReleaser. DO NOT EDIT.
cask "gripmock" do
  version "3.11.1"

  on_macos do
    on_intel do
      sha256 "92b700e8cf7dc7df1de5a407d42c64c4deac2511b9df4dce054887feff8b3d05"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/bavix/gripmock"
    end
    on_arm do
      sha256 "a800fe50f745a1345bb1a908083161a256b314025b2c58c51aa329f04f7e5b61"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/bavix/gripmock"
    end
  end

  on_linux do
    on_intel do
      sha256 "9f4b47d64126d3e8e59434b37be78f9bdb954c851051654480671231504b2873"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock_#{version}_linux_amd64.tar.gz",
        verified: "github.com/bavix/gripmock"
    end
    on_arm do
      sha256 "e713ded1c930a74059c6e02dd1d83cc85a243a771662466060d9d409a52b9fb5"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock_#{version}_linux_arm64.tar.gz",
        verified: "github.com/bavix/gripmock"
    end
  end

  name "gripmock"
  desc "A mock server for gRPC services using .proto files or compiled .pb descriptors"
  homepage "https://bavix.github.io/gripmock/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gripmock"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gripmock"]
    end
  end

  # No zap stanza required

end
