# This file was generated by GoReleaser. DO NOT EDIT.
cask "gripmock-slim" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "gripmock"]
    end
  end

  version "3.23.0"

  on_macos do
    on_arm do
      sha256 "9738e537920436d1c6e1b8bd4ab86c8d52fb88829112aa17ecdbd53e8921ec06"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock-slim_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ff00cb3790ce6b5804c6d38f358e13a1dda77d1810b7b472524f5f2a583ba88b"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock-slim_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "77a20381cb97f9874dd4fd1187a329823dce812b11ea53dafe914e61a8cd750d"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock-slim_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9446ac122b80b6e285f99752e6f3401ec7901a3935514690895040e051d20329"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock-slim_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gripmock-slim"
  desc "A mock server for gRPC services using .proto files or compiled .pb descriptors (no plugin support)"
  homepage "https://bavix.github.io/gripmock/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "gripmock",
    ]

  binary "gripmock-slim"

  # No zap stanza required

  caveats <<~EOS
    Built without cgo: Go plugins (--plugins) are not supported.
    For plugin support run: brew install --cask gripmock
  EOS
end
