# This file was generated by GoReleaser. DO NOT EDIT.
cask "gripmock-slim" do
  version "3.23.2"

  on_macos do
    on_arm do
      sha256 "b494ffc97c51806ffc6b34de8b6eb4db8e66ad44171f356f33f50f66a7b7a74b"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock-slim_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "05a0de676c884605b29a2e8e062e37549758e60100c40ed5b3e4539a56e6ca5e"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock-slim_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "20078cead1c59ecd2a413b1717094f9d73e883a93a7e9339789d28b9d1dd1842"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock-slim_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cba0ff933e71592e4e7586983914b896828df11b3be0c2f0d1a15fddf1326458"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock-slim_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gripmock-slim"
  desc "A mock server for gRPC services using .proto files or compiled .pb descriptors (no plugin support)"
  homepage "https://bavix.github.io/gripmock/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "gripmock",
    ]

  binary "gripmock-slim"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gripmock"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Built without cgo: Go plugins (--plugins) are not supported.
    For plugin support run: brew install --cask gripmock
  EOS
end
