# This file was generated by GoReleaser. DO NOT EDIT.
cask "gripmock" do
  version "3.14.0"

  on_macos do
    on_intel do
      sha256 "75475996f7f1712e9335a573be28777a815b0e4edd1c7587b37addd05ddbf9c1"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/bavix/gripmock"
    end
    on_arm do
      sha256 "6cff0d93280dea9d42085788d384b52c3a6afeaf952d8a0c590991a0081a58b7"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/bavix/gripmock"
    end
  end

  on_linux do
    on_intel do
      sha256 "d9d4ae09590ad89e55d1c57256f9b4ff411d156662288d7e099f501fcfe5bda9"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock_#{version}_linux_amd64.tar.gz",
        verified: "github.com/bavix/gripmock"
    end
    on_arm do
      sha256 "df3d8cccf6b962d538c84b13951f996d8ee201ab9de01775736d476a250d959e"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock_#{version}_linux_arm64.tar.gz",
        verified: "github.com/bavix/gripmock"
    end
  end

  name "gripmock"
  desc "A mock server for gRPC services using .proto files or compiled .pb descriptors"
  homepage "https://bavix.github.io/gripmock/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gripmock"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gripmock"]
    end
  end

  # No zap stanza required

end
