# This file was generated by GoReleaser. DO NOT EDIT.
cask "gripmock" do
  version "3.17.2"

  on_macos do
    on_intel do
      sha256 "cb57dee2409c011c9ee5f2370a77f3261f8331e1e799cc8cda25d17834d3dee9"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/bavix/gripmock"
    end
    on_arm do
      sha256 "f2b127640e30488ec23e2feb90cc368e3677047e32cb00481ec9d2d6cf623afd"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/bavix/gripmock"
    end
  end

  on_linux do
    on_intel do
      sha256 "7b0d646cba1825cb7113d571911e6de60276d2dcc7815a24c639a5c86d302f7f"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock_#{version}_linux_amd64.tar.gz",
        verified: "github.com/bavix/gripmock"
    end
    on_arm do
      sha256 "1f0ee2ed06d1dcf9220e3673c919f177cfd22ac5630ef4a9d0832bacac88bd21"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock_#{version}_linux_arm64.tar.gz",
        verified: "github.com/bavix/gripmock"
    end
  end

  name "gripmock"
  desc "A mock server for gRPC services using .proto files or compiled .pb descriptors"
  homepage "https://bavix.github.io/gripmock/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gripmock"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gripmock"]
    end
  end

  # No zap stanza required

end
