# This file was generated by GoReleaser. DO NOT EDIT.
cask "gripmock-slim" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", staged_path/"gripmock-slim"]
    end
  end

  version "3.23.1"

  on_macos do
    on_arm do
      sha256 "4611c5f48c44af89be7c4f9847d5eccd4fd2dbe2b75dc9eea4ad6555fef08061"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock-slim_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6e59276f66a8f12b3bbe23e130c50c054b70e1e21140512cfa6d91814d5e90a4"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock-slim_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "202a60ac2618313a9ae2613432e631ed9d31a58b91e3c20f5c63e3e3ef6601a1"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock-slim_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bd47f0246907bb600f2c454c157e1680020a2de324a9d86fab63b836e6751833"
      url "https://github.com/bavix/gripmock/releases/download/v#{version}/gripmock-slim_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gripmock-slim"
  desc "A mock server for gRPC services using .proto files or compiled .pb descriptors (no plugin support)"
  homepage "https://bavix.github.io/gripmock/"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "gripmock",
    ]

  binary "gripmock-slim"

  # No zap stanza required

  caveats <<~EOS
    Built without cgo: Go plugins (--plugins) are not supported.
    For plugin support run: brew install --cask gripmock
  EOS
end
