# This file was generated by GitHub Actions. DO NOT EDIT.
cask "grpctestify" do
  name "grpctestify"
  desc "gRPC testing utility written in Rust"
  homepage "https://github.com/gripmock/grpctestify-rust"
  version "1.4.14"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grpctestify"

  on_macos do
    on_intel do
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v#{version}/grpctestify-macos-amd64.tar.gz",
        verified: "github.com/gripmock/grpctestify-rust"
      sha256 "7cfaa237f871ac6022c74ae1bfa4b712ff096a3552cce3554b40b844233c6031"
    end

    on_arm do
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v#{version}/grpctestify-macos-arm64.tar.gz",
        verified: "github.com/gripmock/grpctestify-rust"
      sha256 "178f3b81b1c4b0f4ca836da2023707a1f6d276ae10fcbbcc38f2a8dbd6d40631"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v#{version}/grpctestify-linux-amd64.tar.gz",
        verified: "github.com/gripmock/grpctestify-rust"
      sha256 "195fd7948325ccdb8d1515dba589915d77a8588f02a708ee33afd107ffc517e5"
    end

    on_arm do
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v#{version}/grpctestify-linux-arm64.tar.gz",
        verified: "github.com/gripmock/grpctestify-rust"
      sha256 "a66b1e059271d93c0afd0477cc5ba2287e619513336daf91e38f856aef7f20d9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grpctestify"]
    end
  end

  # No zap stanza required
end
