# This file was generated by GitHub Actions. DO NOT EDIT.
cask "grpctestify" do
  name "grpctestify"
  desc "gRPC testing utility written in Rust"
  homepage "https://github.com/gripmock/grpctestify-rust"
  version "1.8.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grpctestify"

  on_macos do
    on_intel do
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v#{version}/grpctestify-macos-amd64.tar.gz",
        verified: "github.com/gripmock/grpctestify-rust"
      sha256 "e6b4e367c39f395fde6a9744881b99b77c5a4f8b975062d90b95bc1b57539758"
    end

    on_arm do
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v#{version}/grpctestify-macos-arm64.tar.gz",
        verified: "github.com/gripmock/grpctestify-rust"
      sha256 "def58520a41ed86843b4a0726e6265059149b57ca3a312268535d79ec277468c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v#{version}/grpctestify-linux-amd64.tar.gz",
        verified: "github.com/gripmock/grpctestify-rust"
      sha256 "c30d25cc4c512400e152c519c341da324ff16052034a8a460d69b09f1a7da8a8"
    end

    on_arm do
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v#{version}/grpctestify-linux-arm64.tar.gz",
        verified: "github.com/gripmock/grpctestify-rust"
      sha256 "0030a389c074d383480acf3126b45438c42b76c11128bcdd6a5137b4cc4f2fac"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grpctestify"]
    end
  end

  # No zap stanza required
end
