# This file was generated by GitHub Actions. DO NOT EDIT.
cask "grpctestify" do
  name "grpctestify"
  desc "gRPC testing utility written in Rust"
  homepage "https://github.com/gripmock/grpctestify-rust"
  version "1.8.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grpctestify"

  on_macos do
    on_intel do
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v#{version}/grpctestify-macos-amd64.tar.gz",
        verified: "github.com/gripmock/grpctestify-rust"
      sha256 "38fbf0bb69b6b3bc4988ddd0a940fe6a807d0636f28d87c0041eefc3cd8e8935"
    end

    on_arm do
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v#{version}/grpctestify-macos-arm64.tar.gz",
        verified: "github.com/gripmock/grpctestify-rust"
      sha256 "491ce87a9f9e862c1de223f04d9dc59903d5077d0a461b0e48bdb5e18445e187"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v#{version}/grpctestify-linux-amd64.tar.gz",
        verified: "github.com/gripmock/grpctestify-rust"
      sha256 "591dd1ad6d59a9a2ed6816491722775916e3572103b4a174eb41431403cf7bca"
    end

    on_arm do
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v#{version}/grpctestify-linux-arm64.tar.gz",
        verified: "github.com/gripmock/grpctestify-rust"
      sha256 "81033c720fa3be061460ac8627ab637599c1861df697071a5ec3ee71ab0fc9eb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/grpctestify"]
    end
  end

  # No zap stanza required
end
