# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gripmock < Formula
  desc "A mock server for gRPC services using .proto files or compiled .pb descriptors"
  homepage "https://bavix.github.io/gripmock/"
  version "3.17.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bavix/gripmock/releases/download/v3.17.1/gripmock_3.17.1_darwin_amd64.tar.gz"
      sha256 "5090e6aca929639d6aad644ae2a1b02c790c196673758b0c250353c147173194"

      define_method(:install) do
        bin.install "gripmock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bavix/gripmock/releases/download/v3.17.1/gripmock_3.17.1_darwin_arm64.tar.gz"
      sha256 "f35eade72db91b32dc00d7051235f7c6fc316cbb88c316a73dfed580593f2d4a"

      define_method(:install) do
        bin.install "gripmock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bavix/gripmock/releases/download/v3.17.1/gripmock_3.17.1_linux_amd64.tar.gz"
      sha256 "ded38f2a6102874769e5829ff622cf12c7f2eea9813cf9b1559142fb28238992"
      define_method(:install) do
        bin.install "gripmock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bavix/gripmock/releases/download/v3.17.1/gripmock_3.17.1_linux_arm64.tar.gz"
      sha256 "2b2479654d388917a3753f29439b752b19c073cb996e2f3880742ef9abf45202"
      define_method(:install) do
        bin.install "gripmock"
      end
    end
  end

  deprecate! date: "2026-02-18", because: "moved to cask. Please run `brew install --cask gripmock`"

  def caveats
    <<~EOS
      The 'gripmock' formula is deprecated and will be removed in future versions.
      Please migrate to the cask version:
        brew uninstall gripmock
        brew install --cask gripmock
    EOS
  end

  test do
    assert_match "v#{version}", shell_output("#{bin}/gripmock --version")
  end
end
