# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gripmock < Formula
  desc "A mock server for gRPC services using .proto files or compiled .pb descriptors"
  homepage "https://bavix.github.io/gripmock/"
  version "3.2.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bavix/gripmock/releases/download/v3.2.10/gripmock_3.2.10_darwin_amd64.tar.gz"
      sha256 "980087cc92cfad7c2ac46bd079f3adbeb88369114a40ff0e44aabb802c08228c"

      def install
        bin.install "gripmock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bavix/gripmock/releases/download/v3.2.10/gripmock_3.2.10_darwin_arm64.tar.gz"
      sha256 "2c3d7c18e5b9d5c00791ceece8c87858a892f2ff3f0d90cd1cf29d5076a6ba9f"

      def install
        bin.install "gripmock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bavix/gripmock/releases/download/v3.2.10/gripmock_3.2.10_linux_amd64.tar.gz"
        sha256 "0ce3c89f7aed816d4895d97ad86bca84bbec5f643b96c66796a2bbc4d326a86d"

        def install
          bin.install "gripmock"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bavix/gripmock/releases/download/v3.2.10/gripmock_3.2.10_linux_arm64.tar.gz"
        sha256 "2f4dfc561932f86b44e51657396b80ee76029f0788a9b45434dbfff0eb244e3a"

        def install
          bin.install "gripmock"
        end
      end
    end
  end

  test do
    assert_match "v#{version}", shell_output("#{bin}/gripmock --version")
  end
end
