# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gripmock < Formula
  desc "A mock server for gRPC services using .proto files or compiled .pb descriptors"
  homepage "https://bavix.github.io/gripmock/"
  version "3.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bavix/gripmock/releases/download/v3.13.0/gripmock_3.13.0_darwin_amd64.tar.gz"
      sha256 "7d17c5e88fea21aa35c96cf5aa167f2846d3c7403e60aac3502ad78c8ecede0e"

      define_method(:install) do
        bin.install "gripmock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bavix/gripmock/releases/download/v3.13.0/gripmock_3.13.0_darwin_arm64.tar.gz"
      sha256 "938d77c119ccb1bc9296f0aebadba7b21e3d4a7ad1692c8db6a26beb8768e732"

      define_method(:install) do
        bin.install "gripmock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bavix/gripmock/releases/download/v3.13.0/gripmock_3.13.0_linux_amd64.tar.gz"
      sha256 "da1bc966aa4444800190d5ea8e707991f05a13f09b96735aee5b31a9cf32864a"
      define_method(:install) do
        bin.install "gripmock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bavix/gripmock/releases/download/v3.13.0/gripmock_3.13.0_linux_arm64.tar.gz"
      sha256 "f812073369c1a6fb3d2f29375c0641fa2f483040beebca7e0a0496d55e422330"
      define_method(:install) do
        bin.install "gripmock"
      end
    end
  end

  deprecate! date: "2026-02-18", because: "moved to cask. Please run `brew install --cask gripmock`"

  def caveats
    <<~EOS
      The 'gripmock' formula is deprecated and will be removed in future versions.
      Please migrate to the cask version:
        brew uninstall gripmock
        brew install --cask gripmock
    EOS
  end

  test do
    assert_match "v#{version}", shell_output("#{bin}/gripmock --version")
  end
end
