# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class Grpctestify < Formula
  desc "gRPC testing utility written in Rust"
  homepage "https://github.com/gripmock/grpctestify-rust"
  version "1.4.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v1.4.11/grpctestify-macos-amd64.tar.gz"
      sha256 "76707f03bcadc453d33bc7d10025e80aac8138a058e7fadd0f5bee70320dd367"

      def install
        bin.install "grpctestify"
      end
    end

    if Hardware::CPU.arm?
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v1.4.11/grpctestify-macos-arm64.tar.gz"
      sha256 "a2de3f677a031c86c3e0ca9bde83b5023410aeadd9d8d06e78243f94a5d274bc"

      def install
        bin.install "grpctestify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v1.4.11/grpctestify-linux-amd64.tar.gz"
      sha256 "5b3fad7ea8b9bae2ff7bbc0fd92f9aed0c2122fd127627bdbcaf7ae390688c6a"

      def install
        bin.install "grpctestify"
      end
    end

    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v1.4.11/grpctestify-linux-arm64.tar.gz"
      sha256 "79d484c6db3eec1070218dc9f5b214c9ee97425eb0a76e4de008987a04694271"

      def install
        bin.install "grpctestify"
      end
    end
  end

  deprecate! date: "2027-12-31", because: "moved to cask. Please run "

  def caveats
    <<~EOS
      The 'grpctestify' formula is deprecated and will be removed in future versions.
      Please migrate to the cask version:
        brew uninstall grpctestify
        brew install --cask grpctestify
    EOS
  end

  test do
    assert_match "#{version}", shell_output("#{bin}/grpctestify --version")
  end
end
