# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class Grpctestify < Formula
  desc "gRPC testing utility written in Rust"
  homepage "https://github.com/gripmock/grpctestify-rust"
  version "1.4.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v1.4.6/grpctestify-macos-amd64.tar.gz"
      sha256 "cc1de390cc11eb7e125140f1a7dfd36fbf5a5df4790aa25a651e0ae99ac2a748"

      def install
        bin.install "grpctestify"
      end
    end

    if Hardware::CPU.arm?
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v1.4.6/grpctestify-macos-arm64.tar.gz"
      sha256 "4ba70baf59c9adc8c2f3cf8ed88b129a56efcdd325b4101ddfd9f827bf4ae18c"

      def install
        bin.install "grpctestify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v1.4.6/grpctestify-linux-amd64.tar.gz"
      sha256 "146f2618f07f7a831dbb8ed9df2c771dd9f78477c4feadb6eb9fe0c8a8cf48e1"

      def install
        bin.install "grpctestify"
      end
    end

    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v1.4.6/grpctestify-linux-arm64.tar.gz"
      sha256 "013b0767db6e2843f0931c7b43c751752e1d0071c0801224d2cf14d0a4255e23"

      def install
        bin.install "grpctestify"
      end
    end
  end

  deprecate! date: "2027-12-31", because: "moved to cask. Please run "

  def caveats
    <<~EOS
      The 'grpctestify' formula is deprecated and will be removed in future versions.
      Please migrate to the cask version:
        brew uninstall grpctestify
        brew install --cask grpctestify
    EOS
  end

  test do
    assert_match "#{version}", shell_output("#{bin}/grpctestify --version")
  end
end
