# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
class Grpctestify < Formula
  desc "gRPC testing utility written in Rust"
  homepage "https://github.com/gripmock/grpctestify-rust"
  version "1.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v1.7.1/grpctestify-macos-amd64.tar.gz"
      sha256 "8195c9cf80d75b6213fec91b4d5e56fedb24fdf0bc903be2e5f5dfcfa2f8ed43"

      def install
        bin.install "grpctestify"
      end
    end

    if Hardware::CPU.arm?
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v1.7.1/grpctestify-macos-arm64.tar.gz"
      sha256 "4773ce80ee8a9d1e1ab8f7854103acedfdc75b07380a8885689ce7d2cc342f20"

      def install
        bin.install "grpctestify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v1.7.1/grpctestify-linux-amd64.tar.gz"
      sha256 "a61d0a361903723c06896e55331a3e0f46cb7629164499fafe5990c83caa8bd0"

      def install
        bin.install "grpctestify"
      end
    end

    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gripmock/grpctestify-rust/releases/download/v1.7.1/grpctestify-linux-arm64.tar.gz"
      sha256 "8d7361838cca06a25145c98bca80507998095962b3dcf6fd9498e722c7f4ce94"

      def install
        bin.install "grpctestify"
      end
    end
  end

  deprecate! date: "2027-12-31", because: "moved to cask. Please run "

  def caveats
    <<~EOS
      The 'grpctestify' formula is deprecated and will be removed in future versions.
      Please migrate to the cask version:
        brew uninstall grpctestify
        brew install --cask grpctestify
    EOS
  end

  test do
    assert_match "#{version}", shell_output("#{bin}/grpctestify --version")
  end
end
