# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Outway < Formula
  desc "DNS proxy that marks destination IPs and routes by interface"
  homepage "https://github.com/bavix/outway"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bavix/outway/releases/download/v1.2.0/outway_1.2.0_darwin_amd64.tar.gz"
      sha256 "beeb59c11803ed6e3a70bb9cfe0f0bf0b09111be9ef618c433fb57855b87e95f"

      def install
        bin.install "outway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bavix/outway/releases/download/v1.2.0/outway_1.2.0_darwin_arm64.tar.gz"
      sha256 "a0aed3cb588ce5c399ff58e53591adee7793c977d0733882071e26489d4f5283"

      def install
        bin.install "outway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bavix/outway/releases/download/v1.2.0/outway_1.2.0_linux_amd64.tar.gz"
      sha256 "b21a1357d049d68e1cdf9c6a7a8e417f538798356bb23df245f2a593f960ab4f"
      def install
        bin.install "outway"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/bavix/outway/releases/download/v1.2.0/outway_1.2.0_linux_arm6.tar.gz"
      sha256 "91ce4e6801baa34c2c7fbe73e92af3a927b3acd24e9800382e8ec9045e168ed5"
      def install
        bin.install "outway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bavix/outway/releases/download/v1.2.0/outway_1.2.0_linux_arm64.tar.gz"
      sha256 "53ad213150d30314551fcd61f37fdb6194b88590302372ff5cb5e9479daa8ae4"
      def install
        bin.install "outway"
      end
    end
  end

  test do
    assert_match "v#{version}", shell_output("#{bin}/outway version")
  end
end
